---
language: python
services: docker

env:
  global:
    - ROLE_NAME: redis
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME steve.$ROLE_NAME
  - cd steve.$ROLE_NAME

script:
  # Run tests.
  - molecule converge
  - molecule --debug idempotence

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
