---
- name: install debian dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - make
    - libc6-dev
    # This should be `else omit`, but it fails on Ansible 1.x, so just duplicate gcc
    - "{{ 'libc6-dev-i386' if redis_make_32bit|bool else 'gcc' }}"
  when: ansible_os_family == "Debian"

- name: install redhat dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
  when: ansible_os_family == "RedHat"

- name: install suse dependencies
  zypper:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
    # This should be `else omit`, but it fails on Ansible 1.x, so just duplicate gcc
    - "{{ 'gcc-32bit' if redis_make_32bit|bool else 'gcc' }}"
    - "{{ 'libgcc_s1-32bit' if redis_make_32bit|bool else 'gcc' }}"
  when: ansible_os_family == 'Suse'
