---
# tasks file for demo
- include_tasks: variables.yml

- include_tasks: dependencies.yml
  tags:
    - install

- include_tasks: install.yml
  tags:
    - install

- include_tasks: server.yml
  when: not redis_sentinel
  tags:
    - config
