---
- name: Reload systemd daemon
  systemd: daemon_reload=yes

- name: Start and enable redis
  service:
    name: "{{ redis_service_name }}"
    enabled: yes

- name: "restart redis {{ redis_port }}"
  service:
    name: "{{ redis_service_name }}"
    state: restarted

- name: "restart sentinel {{ redis_sentinel_port }}"
  service:
    name: sentinel_{{ redis_sentinel_port }}
    state: restarted
